apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../postgres-cluster
patches:
  - target:
      group: barmancloud.cnpg.io
      version: v1
      kind: ObjectStore
      name: postgres-backups
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: s3://baukit-local/postgres
      - op: add
        path: /spec/configuration/endpointURL
        value: http://minio.postgres.svc.cluster.local:9000
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: postgres-cluster
    patch: |-
      - op: replace
        path: /spec/resources/requests/memory
        value: 192Mi
      - op: replace
        path: /spec/resources/limits/cpu
        value: 300m
      - op: replace
        path: /spec/resources/limits/memory
        value: 384Mi
      - op: replace
        path: /spec/storage/size
        value: 2Gi
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: postgres-restore-test
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/image
        value: rancher/k3s:v1.34.8-k3s1
