import type { DesignTokens, ThemeColor } from './schema.js';

interface FlatToken {
  readonly path: string;
  readonly value: number | string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function isThemeColor(value: unknown): value is ThemeColor {
  return isRecord(value) && typeof value['light'] === 'string' && typeof value['dark'] === 'string';
}

function flattenColors(
  value: unknown,
  path: readonly string[],
  theme: 'light' | 'dark',
  output: FlatToken[],
): void {
  if (isThemeColor(value)) {
    output.push({ path: path.join('-'), value: value[theme] });
    return;
  }
  if (isRecord(value)) {
    for (const key of Object.keys(value).sort()) {
      flattenColors(value[key], [...path, key], theme, output);
    }
  }
}

function flattenScalars(value: unknown, path: readonly string[], output: FlatToken[]): void {
  if (typeof value === 'string' || typeof value === 'number') {
    output.push({ path: path.join('-'), value });
    return;
  }
  if (isRecord(value)) {
    for (const key of Object.keys(value).sort()) {
      flattenScalars(value[key], [...path, key], output);
    }
  }
}

function kebabCase(path: string): string {
  return path.replaceAll(/([a-z\d])([A-Z])/gu, '$1-$2').toLowerCase();
}

function declaration(token: FlatToken): string {
  return `  --bk-${kebabCase(token.path)}: ${String(token.value)};`;
}

function comparePaths(left: FlatToken, right: FlatToken): number {
  return left.path < right.path ? -1 : left.path > right.path ? 1 : 0;
}

/** Compiles a deterministic light root and dark-theme override block. */
export function toCssVariables(tokens: DesignTokens): string {
  const light: FlatToken[] = [];
  const dark: FlatToken[] = [];
  flattenColors(tokens.color, ['color'], 'light', light);
  flattenColors(tokens.color, ['color'], 'dark', dark);
  for (const group of ['typography', 'space', 'radius', 'motion', 'elevation'] as const) {
    flattenScalars(tokens[group], [group], light);
  }
  light.sort(comparePaths);
  dark.sort(comparePaths);

  return [
    ':root {',
    ...light.map(declaration),
    '}',
    '',
    '[data-theme="dark"] {',
    ...dark.map(declaration),
    '}',
    '',
  ].join('\n');
}

function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item: unknown) => sortDeep(item));
  }
  if (isRecord(value)) {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, sortDeep(value[key])]),
    );
  }
  return value;
}

/** Compiles deterministic, nested TypeScript constants for React Native. */
export function toReactNative(tokens: DesignTokens): string {
  const runtimeTokens = {
    color: tokens.color,
    typography: tokens.typography,
    space: tokens.space,
    radius: tokens.radius,
    motion: tokens.motion,
    elevation: tokens.elevation,
  };
  const json = JSON.stringify(sortDeep(runtimeTokens), undefined, 2);
  return `// Generated by @baukit/ui-tokens. Do not edit.\nexport const tokens = ${json} as const;\n\nexport type Tokens = typeof tokens;\n`;
}
