import { describe, expect, it } from 'vitest';

import {
  checkContrast,
  contrastRatio,
  exampleTokens,
  parseTokens,
  relativeLuminance,
  toCssVariables,
  toReactNative,
  TokenValidationError,
  validateTokens,
  type DesignTokens,
} from './index.js';

const minimalTokens = {
  color: {
    background: { primary: { light: '#fff', dark: '#000' } },
    text: { primary: { light: '#000', dark: '#fff' } },
  },
  typography: {
    family: { body: 'Inter' },
    size: { body: 16 },
    weight: { regular: 400 },
    lineHeight: { body: 1.5 },
  },
  space: { small: 8 },
  radius: { small: 4 },
  motion: { duration: { fast: 120 }, easing: { standard: 'linear' } },
  elevation: { raised: 2 },
  contrastPairs: [{ foreground: 'color.text.primary', background: 'color.background.primary' }],
} as const satisfies DesignTokens;

describe('token validation', () => {
  it('accepts the example token set', () => {
    expect(validateTokens(exampleTokens)).toEqual([]);
    expect(parseTokens(exampleTokens)).toBe(exampleTokens);
  });

  it('reports path-qualified structural and scalar errors', () => {
    const invalid = {
      ...exampleTokens,
      typography: {
        ...exampleTokens.typography,
        size: { body: -1 },
      },
      motion: {
        ...exampleTokens.motion,
        easing: { 'Bad Name': '' },
      },
    };
    expect(validateTokens(invalid)).toEqual(
      expect.arrayContaining([
        {
          path: '$.typography.size.body',
          message: 'must be a valid positive dimension',
        },
        {
          path: '$.motion.easing.Bad Name',
          message: 'must start with a lowercase letter and contain only letters or digits',
        },
        { path: '$.motion.easing.Bad Name', message: 'must be a valid string' },
      ]),
    );
  });

  it('rejects invalid colors and unresolved contrast references with exact paths', () => {
    const invalid = {
      ...exampleTokens,
      color: {
        ...exampleTokens.color,
        text: { primary: { light: 'black', dark: '#fff' } },
      },
      contrastPairs: [{ foreground: 'color.text.missing', background: 'color.background.primary' }],
    };
    expect(validateTokens(invalid)).toEqual(
      expect.arrayContaining([
        {
          path: '$.color.text.primary.light',
          message: 'must be a #RGB or #RRGGBB hexadecimal color',
        },
        {
          path: '$.contrastPairs[0].foreground',
          message: 'must reference an existing color token path',
        },
      ]),
    );
  });

  it('throws an aggregate TokenValidationError from parseTokens', () => {
    expect(() => parseTokens(null)).toThrow(TokenValidationError);
    expect(() => parseTokens(null)).toThrow('$: must be an object');
  });
});

describe('CSS compiler', () => {
  it('emits exact deterministic CSS', () => {
    expect(toCssVariables(minimalTokens)).toBe(`:root {
  --bk-color-background-primary: #fff;
  --bk-color-text-primary: #000;
  --bk-elevation-raised: 2;
  --bk-motion-duration-fast: 120;
  --bk-motion-easing-standard: linear;
  --bk-radius-small: 4;
  --bk-space-small: 8;
  --bk-typography-family-body: Inter;
  --bk-typography-line-height-body: 1.5;
  --bk-typography-size-body: 16;
  --bk-typography-weight-regular: 400;
}

[data-theme="dark"] {
  --bk-color-background-primary: #000;
  --bk-color-text-primary: #fff;
}
`);
  });

  it('emits semantic variables and a dark override', () => {
    const css = toCssVariables(exampleTokens);
    expect(css).toContain(':root {\n  --bk-color-background-accent: #005fcc;');
    expect(css).toContain('--bk-typography-line-height-body: 1.5;');
    expect(css).toContain('[data-theme="dark"] {\n  --bk-color-background-accent: #66aaff;');
    expect(css.endsWith('\n')).toBe(true);
  });

  it('is deterministic regardless of object insertion order', () => {
    const reordered = {
      ...exampleTokens,
      space: { medium: 16, small: 8 },
      color: {
        text: exampleTokens.color.text,
        background: exampleTokens.color.background,
      },
    } satisfies DesignTokens;
    expect(toCssVariables(reordered)).toBe(toCssVariables(exampleTokens));
  });
});

describe('React Native compiler', () => {
  it('emits an exact typed constants module', () => {
    expect(toReactNative(minimalTokens)).toBe(`// Generated by @baukit/ui-tokens. Do not edit.
export const tokens = {
  "color": {
    "background": {
      "primary": {
        "dark": "#000",
        "light": "#fff"
      }
    },
    "text": {
      "primary": {
        "dark": "#fff",
        "light": "#000"
      }
    }
  },
  "elevation": {
    "raised": 2
  },
  "motion": {
    "duration": {
      "fast": 120
    },
    "easing": {
      "standard": "linear"
    }
  },
  "radius": {
    "small": 4
  },
  "space": {
    "small": 8
  },
  "typography": {
    "family": {
      "body": "Inter"
    },
    "lineHeight": {
      "body": 1.5
    },
    "size": {
      "body": 16
    },
    "weight": {
      "regular": 400
    }
  }
} as const;

export type Tokens = typeof tokens;
`);
  });

  it('emits a typed nested constants module without accessibility metadata', () => {
    const output = toReactNative(exampleTokens);
    expect(output).toContain(
      '// Generated by @baukit/ui-tokens. Do not edit.\nexport const tokens = {',
    );
    expect(output).toContain('"primary": {\n        "dark": "#111111",');
    expect(output).not.toContain('contrastPairs');
    expect(output).toMatch(/as const;\n\nexport type Tokens = typeof tokens;\n$/u);
  });

  it('sorts nested objects deterministically', () => {
    const reordered = {
      ...exampleTokens,
      radius: { pill: 999, small: 4 },
    } satisfies DesignTokens;
    expect(toReactNative(reordered)).toBe(toReactNative(exampleTokens));
  });
});

describe('WCAG contrast', () => {
  it('calculates the known black/white ratio of 21', () => {
    expect(relativeLuminance('#000000')).toBe(0);
    expect(relativeLuminance('#ffffff')).toBe(1);
    expect(contrastRatio('#000', '#fff')).toBe(21);
  });

  it('accepts all declared example pairs', () => {
    expect(checkContrast(exampleTokens)).toEqual([]);
  });

  it('reports actual ratios and thresholds for each failing theme', () => {
    const failing: DesignTokens = {
      ...exampleTokens,
      color: {
        ...exampleTokens.color,
        text: {
          ...exampleTokens.color.text,
          weak: { light: '#777777', dark: '#777777' },
        },
      },
      contrastPairs: [{ foreground: 'color.text.weak', background: 'color.background.primary' }],
    };
    const violations = checkContrast(failing);
    expect(violations).toHaveLength(2);
    expect(violations[0]).toMatchObject({
      foreground: 'color.text.weak',
      theme: 'light',
      requiredRatio: 4.5,
    });
    expect(violations[0]?.ratio).toBeCloseTo(4.478, 3);
    expect(violations[1]).toMatchObject({ theme: 'dark', requiredRatio: 4.5 });
  });

  it('uses the 3:1 threshold for declared large text', () => {
    const largeText: DesignTokens = {
      ...exampleTokens,
      color: {
        ...exampleTokens.color,
        text: {
          ...exampleTokens.color.text,
          large: { light: '#767676', dark: '#888888' },
        },
      },
      contrastPairs: [
        {
          foreground: 'color.text.large',
          background: 'color.background.primary',
          largeText: true,
        },
      ],
    };
    expect(checkContrast(largeText)).toEqual([]);
  });
});
