apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: platform-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: baukit-platform
    baukit.dev/component: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: platform-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: baukit-platform
    baukit.dev/component: redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
    - name: sentinel
      port: 26379
      targetPort: sentinel
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: platform-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: baukit-platform
    baukit.dev/component: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: sentinel
      port: 26379
      targetPort: sentinel
      protocol: TCP
