apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../traefik
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: traefik
    patch: |-
      - op: replace
        path: /spec/values/resources/requests/cpu
        value: 25m
      - op: replace
        path: /spec/values/resources/requests/memory
        value: 48Mi
      - op: replace
        path: /spec/values/resources/limits/cpu
        value: 300m
      - op: replace
        path: /spec/values/resources/limits/memory
        value: 192Mi

