// Generated by @baukit/ui-tokens. Do not edit.
export const tokens = {
  "color": {
    "background": {
      "accent": {
        "dark": "#66aaff",
        "light": "#005fcc"
      },
      "primary": {
        "dark": "#111111",
        "light": "#ffffff"
      }
    },
    "text": {
      "onAccent": {
        "dark": "#111111",
        "light": "#ffffff"
      },
      "primary": {
        "dark": "#ffffff",
        "light": "#111111"
      }
    }
  },
  "elevation": {
    "raised": "0 2px 8px rgb(0 0 0 / 0.2)"
  },
  "motion": {
    "duration": {
      "fast": "120ms",
      "normal": "240ms"
    },
    "easing": {
      "standard": "cubic-bezier(0.2, 0, 0, 1)"
    }
  },
  "radius": {
    "pill": 999,
    "small": 4
  },
  "space": {
    "medium": 16,
    "small": 8
  },
  "typography": {
    "family": {
      "body": "Inter, sans-serif"
    },
    "lineHeight": {
      "body": 1.5,
      "title": 1.2
    },
    "size": {
      "body": "1rem",
      "title": "2rem"
    },
    "weight": {
      "bold": 700,
      "regular": 400
    }
  }
} as const;

export type Tokens = typeof tokens;
