apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - plugin-barman-cloud-v0.14.0.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: barman-cloud
      namespace: cnpg-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

