apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baukit-observability
  namespace: observability
spec:
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  chart:
    spec:
      chart: ./deploy/observability
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: baukit
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    dashboardConfigMap:
      enabled: true
      labels:
        grafana_dashboard: "1"
    ruleConfigMaps:
      enabled: true
    prometheusRule:
      enabled: true

