allowBuilds:
  core-js: false
{% if context.auth_clerk %}  browser-tabs-lock: false
{% endif %}
  unrs-resolver: true

catalog:
  expo-constants: 57.0.21

overrides:
  '@react-native/metro-config': 0.86.3
  expo-constants: 'catalog:'
  react-dom: 19.2.3

peerDependencyRules:
  allowedVersions:
    'eslint-plugin-react-native-a11y>eslint': '10'
