apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: posthog-default-deny-ingress
  namespace: posthog
spec:
  podSelector: {}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: posthog-internal-ingress
  namespace: posthog
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: posthog-traefik-ingress
  namespace: posthog
spec:
  podSelector:
    matchExpressions:
      - key: role
        operator: In
        values: [web, events]
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8000
