apiVersion: v1
kind: Service
metadata:
  name: posthog-pgbouncer
  namespace: posthog
  labels:
    app.kubernetes.io/name: posthog-postgresql
    app.kubernetes.io/part-of: baukit-platform
    baukit.dev/component: analytics
spec:
  selector:
    app.kubernetes.io/name: posthog-postgresql
    app.kubernetes.io/part-of: baukit-platform
    baukit.dev/component: analytics
  ports:
    - name: pgbouncer-compat
      port: 6543
      targetPort: postgres
