apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: baukit
  namespace: flux-system
spec:
  interval: 1m
  timeout: 1m
  url: http://host.k3d.internal:9418/baukit.git
  ref:
    branch: main
