apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - namespace.yaml
  - cluster.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - pushgateway.yaml
  - restore-test.yaml
  - prometheusrule.yaml

